name: mlops-insolvency-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - pyyaml
  - openpyxl
  - pip:
      - joblib
      - azureml-inference-server-http